services:
  crealityprint:
    image: ghcr.io/riddix/docker-creality-slicer-master:latest
    container_name: crealityprint
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
      # Intel iGPU settings
      - DRINODE=/dev/dri/renderD128
      - DRI_NODE=/dev/dri/renderD128
    volumes:
      - ./config:/config
    ports:
      - 3000:3000
      - 3001:3001
      # Creality Print printer communication (TCP) and mDNS discovery (UDP)
      - 9999:9999
      - 5353:5353/udp
    devices:
      - /dev/dri:/dev/dri
    shm_size: 4gb
    restart: unless-stopped
